### ISSUE TITLE
npm start day1 throwing errors

### ISSUE THREAD

**Issue by bogga** [caderek/aoc-starter-js#1]
Running node 14.15.1 on win10

If I run `npm start day1`, node spits this out (after creating the folder & files if necessary)

```
> node ./scripts/start.js "day1"

events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: spawn nodemon ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
    at onErrorNT (internal/child_process.js:465:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
    at onErrorNT (internal/child_process.js:465:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'spawn nodemon',
  path: 'nodemon',
  spawnargs: [ 'src\\day1\\index.js' ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! aoc2019@1.0.0 start: `node ./scripts/start.js "day1"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the aoc2019@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by Kaishiyoku** [comment]
The issue lies in src/utils/readInput.js line 6:

`split("/")` does not work under Windows 10, if you replace it with `split('\\')' it's working.

**Comment by Kaishiyoku** [comment]
Also, try using `node` instead of `nodemon` when spawning a new process in the `start.js`.

**Comment by bogga** [comment]
If I use `.split("\\")` and replace `nodemon` with `node` it works, thanks! Would prefer nodemon to work but oh well 👍

**Comment by Kaishiyoku** [comment]
@bogga Yeah, me too. I didn't have the time yet to figure that out, but will probably take a look at it.

**Comment by bogga** [comment]
Nice, would appreciate it!

**Comment by Kaishiyoku** [comment]
@bogga I opened a pull request for that: #2

**Comment by bogga** [comment]
nice work @Kaishiyoku!
